---
- name: MySQL | Install
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  register: install

- name: MySQL | Delete conf
  file:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    state: absent
  when: install.changed

- name: MySQL | mysqld Configure
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  register: configure

- name: Configure update
  when: configure.changed
  include_tasks: config.yml
